#!/usr/bin/env swift
//
//  makesprite.swift — generates Resources/sprites/cat_*.png (+ sidecars).
//
//  Standalone, like dockprobe.swift and makeicon.swift; not part of the app target.
//
//  Draws at the pixel level rather than with antialiased shapes: every routine here writes
//  whole pixels into a 32x32 grid, so the result is real pixel art rather than a smooth
//  drawing shrunk down. The outline is generated by dilating the silhouette, which keeps a
//  consistent 1 px border around whatever the pose happens to be.
//
//  Four sheets: an 8-frame side-on walk cycle, and one single-frame pose each for idle,
//  sit and sleep. The poses are single-frame on purpose — AppDelegate suspends the 12 fps
//  timer for a stationary state whose sheet has nothing to animate, so a still pose costs
//  nothing to display. Giving one of them a second frame is all it takes to animate it.
//
//  Run with:  swift makesprite.swift
//

import AppKit
import Foundation

_ = NSApplication.shared

// MARK: - Sheet geometry

let frameSize = 32
let walkFrameCount = 8
let fps = 10.0

/// Feet rest here; the dilated outline then occupies row 31, so the cat's outline sits
/// exactly on the bottom edge of the frame — and therefore exactly on the Dock's top edge.
let groundY = 30

// MARK: - Palette

enum Ink: UInt8 {
    case clear = 0
    case outline = 1
    case coat = 2        // main orange
    case stripe = 3      // darker tabby banding
    case belly = 4       // cream chest and underside
    case farLimb = 5     // shaded orange for the off-side legs, for depth
    case pink = 6        // nose, inner ear, paw pads
    case eye = 7

    var rgba: (UInt8, UInt8, UInt8, UInt8) {
        switch self {
        case .clear:   return (0, 0, 0, 0)
        case .outline: return (0x2B, 0x20, 0x18, 0xFF)
        case .coat:    return (0xE8, 0x95, 0x4A, 0xFF)
        case .stripe:  return (0xC4, 0x6B, 0x26, 0xFF)
        case .belly:   return (0xF7, 0xDC, 0xB4, 0xFF)
        case .farLimb: return (0xB8, 0x63, 0x24, 0xFF)
        case .pink:    return (0xE8, 0x90, 0xA0, 0xFF)
        case .eye:     return (0x3E, 0x6B, 0x35, 0xFF)
        }
    }
}

// MARK: - Pixel grid

struct Grid {
    var px: [Ink]
    let size: Int

    init(size: Int) {
        self.size = size
        self.px = Array(repeating: .clear, count: size * size)
    }

    subscript(x: Int, y: Int) -> Ink {
        get {
            guard x >= 0, y >= 0, x < size, y < size else { return .clear }
            return px[y * size + x]
        }
        set {
            guard x >= 0, y >= 0, x < size, y < size else { return }
            px[y * size + x] = newValue
        }
    }

    mutating func fillEllipse(cx: Double, cy: Double, rx: Double, ry: Double, _ ink: Ink) {
        let x0 = Int((cx - rx).rounded(.down)), x1 = Int((cx + rx).rounded(.up))
        let y0 = Int((cy - ry).rounded(.down)), y1 = Int((cy + ry).rounded(.up))
        for y in y0...y1 {
            for x in x0...x1 {
                let dx = (Double(x) + 0.5 - cx) / rx
                let dy = (Double(y) + 0.5 - cy) / ry
                if dx * dx + dy * dy <= 1.0 { self[x, y] = ink }
            }
        }
    }

    mutating func fillRect(x0: Int, y0: Int, x1: Int, y1: Int, _ ink: Ink) {
        for y in min(y0, y1)...max(y0, y1) {
            for x in min(x0, x1)...max(x0, x1) { self[x, y] = ink }
        }
    }

    /// A line of square caps — the pixel-art equivalent of a stroked path.
    mutating func stroke(from p0: (Double, Double), to p1: (Double, Double),
                         width: Double, _ ink: Ink) {
        let steps = max(1, Int((abs(p1.0 - p0.0) + abs(p1.1 - p0.1)) * 2))
        for i in 0...steps {
            let t = Double(i) / Double(steps)
            let x = p0.0 + (p1.0 - p0.0) * t
            let y = p0.1 + (p1.1 - p0.1) * t
            let r = width / 2
            let xi0 = Int((x - r).rounded()), xi1 = Int((x + r - 0.01).rounded())
            let yi0 = Int((y - r).rounded()), yi1 = Int((y + r - 0.01).rounded())
            for yy in yi0...max(yi0, yi1) {
                for xx in xi0...max(xi0, xi1) { self[xx, yy] = ink }
            }
        }
    }

    mutating func triangle(_ a: (Int, Int), _ b: (Int, Int), _ c: (Int, Int), _ ink: Ink) {
        let minX = min(a.0, b.0, c.0), maxX = max(a.0, b.0, c.0)
        let minY = min(a.1, b.1, c.1), maxY = max(a.1, b.1, c.1)
        func edge(_ p: (Int, Int), _ q: (Int, Int), _ x: Double, _ y: Double) -> Double {
            (x - Double(p.0)) * Double(q.1 - p.1) - (y - Double(p.1)) * Double(q.0 - p.0)
        }
        for y in minY...maxY {
            for x in minX...maxX {
                let fx = Double(x) + 0.5, fy = Double(y) + 0.5
                let e0 = edge(a, b, fx, fy), e1 = edge(b, c, fx, fy), e2 = edge(c, a, fx, fy)
                if (e0 >= 0 && e1 >= 0 && e2 >= 0) || (e0 <= 0 && e1 <= 0 && e2 <= 0) {
                    self[x, y] = ink
                }
            }
        }
    }

    /// Composite `shape` onto this grid with its own 1 px outline.
    ///
    /// Each body part is stamped separately rather than outlining one merged silhouette.
    /// That is what makes a leg read as a leg instead of dissolving into the body: the
    /// leg's own outline draws over the coat behind it, separating the two.
    mutating func stamp(fill: Ink, outline: Ink = .outline, _ shape: (inout Grid) -> Void) {
        var part = Grid(size: size)
        shape(&part)

        let ring = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)]
        var border: [(Int, Int)] = []
        for y in 0..<size {
            for x in 0..<size where part[x, y] == .clear {
                if ring.contains(where: { part[x + $0.0, y + $0.1] != .clear }) {
                    border.append((x, y))
                }
            }
        }
        for (x, y) in border { self[x, y] = outline }
        for y in 0..<size {
            for x in 0..<size where part[x, y] != .clear { self[x, y] = fill }
        }
    }
}

/// Paint a marking over coat only, so it can never spill past an outline.
func tint(_ g: inout Grid, _ ink: Ink, _ shape: (inout Grid) -> Void) {
    var mask = Grid(size: g.size)
    shape(&mask)
    for y in 0..<g.size {
        for x in 0..<g.size where mask[x, y] != .clear && g[x, y] == .coat {
            g[x, y] = ink
        }
    }
}

// MARK: - Bicolour white

/// Turn every coat pixel below `y` white — the socks and underside of a bicolour cat.
///
/// This lives in the art rather than in `CatPalette` because a palette can only recolour
/// the regions the sheet already has, never resize them. The sheet spent 85% of its body
/// pixels on `coat` and 13% on `belly`, so no choice of colours could produce a cat that
/// reads as substantially white; the only reachable splits were ~85/13 or ~14/84. Growing
/// the belly region here is what makes a roughly 60/40 coat-to-white cat possible at all.
///
/// Far-side limbs are `.farLimb`, not `.coat`, so `tint` leaves them coloured. That is
/// deliberate: white socks on the near legs and coloured ones behind keeps the depth cue
/// that stops the four legs merging into one pale block.
func whiteSocks(_ g: inout Grid, from y: Int) {
    tint(&g, .belly) { $0.fillRect(x0: 0, y0: y, x1: frameSize - 1, y1: frameSize - 1, .belly) }
}

// MARK: - Walk cycle

/// Where a paw sits at a given point in the cycle.
///
/// Stance is the longer part (paw planted, sliding backwards under the body); swing is
/// quicker and lifts the paw clear of the ground.
func paw(phase: Double, reach: Double) -> (dx: Double, lift: Double) {
    let p = phase - phase.rounded(.down)
    let stance = 0.58
    if p < stance {
        let t = p / stance
        return (reach - 2 * reach * t, 0)                    // front to back, on the ground
    } else {
        let t = (p - stance) / (1 - stance)
        return (-reach + 2 * reach * t, 2.2 * sin(.pi * t))  // back to front, lifted
    }
}

func drawLeg(_ g: inout Grid, hip: (Double, Double), phase: Double, reach: Double, ink: Ink) {
    let step = paw(phase: phase, reach: reach)
    let footX = hip.0 + step.dx
    let footY = Double(groundY) - step.lift
    // Knee slightly ahead of the midpoint so the leg reads as jointed, not as a stick.
    let knee = ((hip.0 + footX) / 2 + 0.7, (hip.1 + footY) / 2)
    g.stamp(fill: ink) { part in
        part.stroke(from: hip, to: knee, width: 2.2, ink)
        part.stroke(from: knee, to: (footX, footY), width: 1.9, ink)
        part.stroke(from: (footX - 0.5, footY), to: (footX + 1.3, footY), width: 1.9, ink)
    }
}

func makeFrame(_ index: Int) -> Grid {
    var g = Grid(size: frameSize)
    let phase = Double(index) / Double(walkFrameCount)

    // The body rises and falls twice per stride.
    let bob = sin(2 * .pi * 2 * phase) > 0.3 ? -1.0 : 0.0

    let bodyCY = 19.0 + bob
    let headCX = 23.2, headCY = 13.2 + bob

    // --- far-side legs first, so the near pair overlaps them ---
    drawLeg(&g, hip: (10.0, bodyCY + 2.5), phase: phase + 0.5, reach: 3.6, ink: .farLimb)
    drawLeg(&g, hip: (17.5, bodyCY + 2.5), phase: phase + 0.75, reach: 3.6, ink: .farLimb)

    // --- tail: thin, sweeping up behind, swaying through the cycle ---
    let sway = sin(2 * .pi * phase)
    // Cubic, so the tail can sweep back and *then* hook upwards. A quadratic here read as
    // a vertical plank once the outline was added.
    let tip = (5.2 + sway * 0.9, 6.6 + sway * 1.2)
    g.stamp(fill: .coat) { part in
        let p0 = (6.4, bodyCY - 1.0)
        let c1 = (1.2, bodyCY - 0.2)
        let c2 = (0.6, 9.0)
        var previous = p0
        for i in 1...14 {
            let t = Double(i) / 14, mt = 1 - t
            let x = mt*mt*mt*p0.0 + 3*mt*mt*t*c1.0 + 3*mt*t*t*c2.0 + t*t*t*tip.0
            let y = mt*mt*mt*p0.1 + 3*mt*mt*t*c1.1 + 3*mt*t*t*c2.1 + t*t*t*tip.1
            part.stroke(from: previous, to: (x, y), width: 1.7 - 0.4 * t, .coat)
            previous = (x, y)
        }
    }

    // --- body, neck, head and ears as one stamp, so no outline runs between them ---
    g.stamp(fill: .coat) { part in
        part.fillEllipse(cx: 13.0, cy: bodyCY, rx: 7.4, ry: 4.4, .coat)
        part.fillEllipse(cx: 18.6, cy: bodyCY - 2.2, rx: 2.8, ry: 3.2, .coat)
        part.fillEllipse(cx: headCX, cy: headCY, rx: 4.3, ry: 4.0, .coat)
        // Small, upright ears. Large triangles made this read as a fox.
        part.triangle((20, Int(headCY) - 6), (20, Int(headCY) - 3), (23, Int(headCY) - 4), .coat)
        part.triangle((26, Int(headCY) - 6), (25, Int(headCY) - 3), (27, Int(headCY) - 4), .coat)
    }

    // --- near-side legs, on top ---
    drawLeg(&g, hip: (11.0, bodyCY + 2.5), phase: phase, reach: 4.0, ink: .coat)
    drawLeg(&g, hip: (18.5, bodyCY + 2.5), phase: phase + 0.25, reach: 4.0, ink: .coat)

    // --- markings: painted only over existing coat, so they never spill past the outline ---
    // The white of a bicolour cat: underside, chest, muzzle, socks and tail tip. See the
    // note above `whiteSocks` for why this is art and not a palette entry.
    tint(&g, .belly) { $0.fillEllipse(cx: 13.0, cy: bodyCY + 3.3, rx: 7.0, ry: 2.7, .belly) }
    tint(&g, .belly) { $0.fillEllipse(cx: 19.2, cy: bodyCY - 0.2, rx: 2.6, ry: 3.2, .belly) }
    tint(&g, .belly) { $0.fillEllipse(cx: 25.6, cy: headCY + 1.8, rx: 2.4, ry: 1.6, .belly) }
    whiteSocks(&g, from: 26)
    tint(&g, .belly) { $0.fillEllipse(cx: tip.0, cy: tip.1, rx: 1.7, ry: 1.7, .belly) }

    // Three thin tabby bars, spaced so they stay separate at this size.
    for bar in 0..<3 {
        let x = 10.0 + Double(bar) * 3.4
        tint(&g, .stripe) { $0.stroke(from: (x, bodyCY - 4.2), to: (x - 0.7, bodyCY - 2.4), width: 1.1, .stripe) }
    }

    // --- details last, so nothing can paint over them ---
    g[Int(headCX) + 2, Int(headCY) - 1] = .eye
    g[27, Int(headCY) + 1] = .pink            // nose
    g[21, Int(headCY) - 4] = .pink            // inner ear, near
    g[26, Int(headCY) - 4] = .pink            // inner ear, far

    return g
}


// MARK: - Stationary poses
//
// A cat that stops walking turns to look at you rather than freezing mid-stride, so idle
// and sit are drawn front-on. Same grid, same palette, same ground line as the walk cycle,
// so a pose drops into the pet's window without moving it.
//
// Sleep is the exception: a curled cat has no front view worth drawing — head-on it is a
// featureless mound — so it is drawn curled up with its head towards you instead.

/// A straight front-on leg, planted on the ground line.
func drawStandingLeg(_ g: inout Grid, x: Double, top: Double, ink: Ink) {
    g.stamp(fill: ink) { part in
        part.stroke(from: (x, top), to: (x, Double(groundY)), width: 2.2, ink)
        part.stroke(from: (x - 1.0, Double(groundY)), to: (x + 1.0, Double(groundY)), width: 1.8, ink)
    }
}

/// A pair of upright ears on a front-on head, centred on the skull.
func drawEars(_ part: inout Grid, cx: Double, cy: Double) {
    let x = Int(cx), y = Int(cy)
    part.triangle((x - 5, y - 7), (x - 5, y - 2), (x - 1, y - 3), .coat)
    part.triangle((x + 5, y - 7), (x + 5, y - 2), (x + 1, y - 3), .coat)
}

/// Muzzle, eyes, nose and inner ears — the half of a head that says "cat looking at you".
///
/// Written last of all, straight into the grid rather than through `tint`, so nothing can
/// paint over the face.
func drawFace(_ g: inout Grid, cx: Double, cy: Double, eyesClosed: Bool = false) {
    let x = Int(cx), y = Int(cy)

    tint(&g, .belly) { $0.fillEllipse(cx: cx, cy: cy + 2.3, rx: 2.7, ry: 1.8, .belly) }

    // Two pixels of eye each side. One pixel reads as a speck at this size; three make the
    // cat look startled.
    for dx in [-3, -2, 2, 3] { g[x + dx, y] = eyesClosed ? .outline : .eye }

    g[x, y + 2] = .pink              // nose
    g[x - 4, y - 4] = .pink          // inner ear, left
    g[x + 4, y - 4] = .pink          // inner ear, right
}

/// Three thin bars across the forehead — the tabby's M, which is what makes a front-on
/// orange cat read as the same animal as the side-on one.
///
/// Single pixels, written one at a time rather than stroked: a stroke rounds out to two
/// pixels wide, and three of those on a ten-pixel skull merge into a dark cap.
func drawForeheadStripes(_ g: inout Grid, cx: Double, cy: Double) {
    let x = Int(cx), y = Int(cy)
    for dx in [-3, 0, 3] {
        for dy in [-4, -3] where g[x + dx, y + dy] == .coat { g[x + dx, y + dy] = .stripe }
    }
}

/// Idle: standing square on, tail curled up behind.
func makeIdlePose() -> Grid {
    var g = Grid(size: frameSize)
    let headCX = 16.0, headCY = 11.5

    // Tail first, so the body covers where it joins.
    g.stamp(fill: .coat) { part in
        let p0 = (19.2, 26.2), c1 = (25.0, 26.8), c2 = (26.4, 18.0), tip = (22.6, 15.2)
        var previous = p0
        for i in 1...14 {
            let t = Double(i) / 14, mt = 1 - t
            let x = mt*mt*mt*p0.0 + 3*mt*mt*t*c1.0 + 3*mt*t*t*c2.0 + t*t*t*tip.0
            let y = mt*mt*mt*p0.1 + 3*mt*mt*t*c1.1 + 3*mt*t*t*c2.1 + t*t*t*tip.1
            part.stroke(from: previous, to: (x, y), width: 1.8 - 0.5 * t, .coat)
            previous = (x, y)
        }
    }

    // Hind legs, shaded, so the front pair reads as nearer.
    drawStandingLeg(&g, x: 11.4, top: 24.0, ink: .farLimb)
    drawStandingLeg(&g, x: 20.6, top: 24.0, ink: .farLimb)

    // Body, chest, head and ears in one stamp — no outline seam down the neck.
    g.stamp(fill: .coat) { part in
        part.fillEllipse(cx: 16.0, cy: 22.4, rx: 5.4, ry: 6.2, .coat)
        part.fillEllipse(cx: 16.0, cy: 17.0, rx: 4.4, ry: 4.2, .coat)
        part.fillEllipse(cx: headCX, cy: headCY, rx: 5.0, ry: 4.5, .coat)
        drawEars(&part, cx: headCX, cy: headCY)
    }

    drawStandingLeg(&g, x: 13.4, top: 25.0, ink: .coat)
    drawStandingLeg(&g, x: 18.6, top: 25.0, ink: .coat)

    // White front, from chin to between the paws, plus socks and tail tip.
    tint(&g, .belly) { $0.fillEllipse(cx: 16.0, cy: 22.8, rx: 3.3, ry: 6.2, .belly) }
    whiteSocks(&g, from: 25)
    tint(&g, .belly) { $0.fillEllipse(cx: 22.6, cy: 15.2, rx: 1.7, ry: 1.7, .belly) }

    // Tabby banding down the flanks, clear of the cream front.
    for side in [-1.0, 1.0] {
        tint(&g, .stripe) {
            $0.stroke(from: (16.0 + side * 4.6, 19.5), to: (16.0 + side * 4.6, 22.0), width: 1.2, .stripe)
        }
    }

    drawForeheadStripes(&g, cx: headCX, cy: headCY)
    drawFace(&g, cx: headCX, cy: headCY)
    return g
}

/// Sit: haunches down, tail curled around the front, paws tucked on top of it.
///
/// The forelegs are *not* stamped as their own shapes here, the way the idle pose stamps
/// its standing legs. A stamp brings its own 1 px outline, and two of them side-on to the
/// viewer put four dark verticals down a chest only ten pixels wide — plus a solid bar
/// where the leg tops meet the body. At this size that reads as a barred window, not as
/// legs. Front-on, a sitting cat's forelegs are mostly hidden behind the tail anyway, so
/// the pose keeps one unbroken silhouette and says "paws" with two cream patches tinted
/// straight into the coat instead.
func makeSitPose() -> Grid {
    var g = Grid(size: frameSize)
    let headCX = 16.0, headCY = 10.5

    // Haunches, chest, head and ears. The haunch ellipse runs past the ground line so its
    // fill reaches row 30 and the dilated outline lands on row 31, like the walking feet.
    g.stamp(fill: .coat) { part in
        part.fillEllipse(cx: 16.0, cy: 25.2, rx: 7.0, ry: 5.6, .coat)
        part.fillEllipse(cx: 16.0, cy: 18.0, rx: 4.8, ry: 5.0, .coat)
        part.fillEllipse(cx: headCX, cy: headCY, rx: 5.0, ry: 4.5, .coat)
        drawEars(&part, cx: headCX, cy: headCY)
    }

    // Tail before the paws, so they rest on its top edge the way tucked paws do.
    g.stamp(fill: .coat) { part in
        let p0 = (22.6, 24.0), c1 = (25.5, 29.0), c2 = (18.0, 31.0), tip = (12.4, 29.4)
        var previous = p0
        for i in 1...14 {
            let t = Double(i) / 14, mt = 1 - t
            let x = mt*mt*mt*p0.0 + 3*mt*mt*t*c1.0 + 3*mt*t*t*c2.0 + t*t*t*tip.0
            let y = mt*mt*mt*p0.1 + 3*mt*mt*t*c1.1 + 3*mt*t*t*c2.1 + t*t*t*tip.1
            part.stroke(from: previous, to: (x, y), width: 1.8 - 0.4 * t, .coat)
            previous = (x, y)
        }
    }

    // Cream front. It stops a row short of the paws so a band of coat separates the two;
    // run them together and the whole chest reads as one cream slab.
    tint(&g, .belly) { $0.fillEllipse(cx: 16.0, cy: 19.8, rx: 3.7, ry: 5.6, .belly) }

    // The paws: colour only, no stamp. Tinting inside the existing silhouette adds no
    // outline of its own, which is the whole point — two pixels of coat between them is
    // all the separation a pair of paws needs at 32x32.
    for cx in [13.3, 18.7] {
        tint(&g, .belly) { $0.fillEllipse(cx: cx, cy: 27.0, rx: 2.6, ry: 1.9, .belly) }
    }
    tint(&g, .belly) { $0.fillEllipse(cx: 12.4, cy: 29.4, rx: 1.7, ry: 1.5, .belly) }

    for side in [-1.0, 1.0] {
        tint(&g, .stripe) {
            $0.stroke(from: (16.0 + side * 5.8, 22.5), to: (16.0 + side * 5.8, 25.0), width: 1.2, .stripe)
        }
    }

    drawForeheadStripes(&g, cx: headCX, cy: headCY)
    drawFace(&g, cx: headCX, cy: headCY)
    return g
}

/// Sleep: curled into a loaf, eyes shut, tail around the front.
func makeSleepPose() -> Grid {
    var g = Grid(size: frameSize)
    let headCX = 9.2, headCY = 23.6

    // The loaf: an ellipse with a flat base, so a sleeping cat settles onto the Dock
    // rather than balancing on a curve.
    g.stamp(fill: .coat) { part in
        part.fillEllipse(cx: 17.5, cy: 24.4, rx: 8.4, ry: 5.4, .coat)
        part.fillRect(x0: 10, y0: 25, x1: 25, y1: groundY, .coat)
    }

    // Head tucked down at the near end, ears folded low the way a sleeping cat holds them.
    g.stamp(fill: .coat) { part in
        part.fillEllipse(cx: headCX, cy: headCY, rx: 4.3, ry: 3.9, .coat)
        part.triangle((5, 18), (5, 22), (9, 21), .coat)
        part.triangle((12, 18), (12, 22), (9, 21), .coat)
    }

    // Tail around the front, drawn last so it reads as nearest.
    g.stamp(fill: .coat) { part in
        let p0 = (25.0, 22.5), c1 = (28.5, 28.5), c2 = (19.0, 31.5), tip = (13.0, 28.6)
        var previous = p0
        for i in 1...14 {
            let t = Double(i) / 14, mt = 1 - t
            let x = mt*mt*mt*p0.0 + 3*mt*mt*t*c1.0 + 3*mt*t*t*c2.0 + t*t*t*tip.0
            let y = mt*mt*mt*p0.1 + 3*mt*mt*t*c1.1 + 3*mt*t*t*c2.1 + t*t*t*tip.1
            part.stroke(from: previous, to: (x, y), width: 1.8 - 0.4 * t, .coat)
            previous = (x, y)
        }
    }

    tint(&g, .belly) { $0.fillEllipse(cx: 18.0, cy: 28.4, rx: 7.9, ry: 3.5, .belly) }
    tint(&g, .belly) { $0.fillEllipse(cx: 13.0, cy: 28.6, rx: 1.8, ry: 1.6, .belly) }
    for bar in 0..<3 {
        let x = 14.0 + Double(bar) * 3.4
        tint(&g, .stripe) { $0.stroke(from: (x, 19.6), to: (x - 0.7, 21.4), width: 1.1, .stripe) }
    }

    // A shut lid instead of an eye, and the muzzle turned towards you.
    g[Int(headCX) - 3, Int(headCY)] = .outline
    g[Int(headCX) - 2, Int(headCY)] = .outline
    tint(&g, .belly) { $0.fillEllipse(cx: headCX - 1.6, cy: headCY + 2.0, rx: 2.2, ry: 1.4, .belly) }
    g[Int(headCX) - 2, Int(headCY) + 2] = .pink      // nose
    g[Int(headCX) - 3, Int(headCY) - 3] = .pink      // inner ear

    return g
}

// MARK: - Encode

/// Write one sheet and its sidecar. Frames run left to right, as SPEC §5 requires.
func writeSheet(name: String, frames: [Grid], to directory: URL) throws {
    let sheetWidth = frameSize * frames.count
    let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: sheetWidth, pixelsHigh: frameSize,
                              bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                              colorSpaceName: .deviceRGB, bytesPerRow: sheetWidth * 4, bitsPerPixel: 32)!
    let data = rep.bitmapData!
    for i in 0..<(sheetWidth * frameSize * 4) { data[i] = 0 }

    for (index, g) in frames.enumerated() {
        for y in 0..<frameSize {
            for x in 0..<frameSize {
                let (r, gg, b, a) = g[x, y].rgba
                let offset = y * rep.bytesPerRow + (index * frameSize + x) * 4
                data[offset] = r; data[offset + 1] = gg; data[offset + 2] = b; data[offset + 3] = a
            }
        }
    }

    let png = directory.appendingPathComponent("\(name).png")
    try rep.representation(using: .png, properties: [:])!.write(to: png)
    let sidecar = #"{"frameWidth":\#(frameSize),"frameHeight":\#(frameSize),"frameCount":\#(frames.count),"fps":\#(fps)}"#
    try sidecar.write(to: directory.appendingPathComponent("\(name).json"),
                      atomically: true, encoding: .utf8)
    print("wrote \(png.path) (\(sheetWidth)x\(frameSize), \(frames.count) frame\(frames.count == 1 ? "" : "s"))")
}

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let dir = root.appendingPathComponent("Resources/sprites")
try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

try writeSheet(name: "cat_walk", frames: (0..<walkFrameCount).map(makeFrame), to: dir)
try writeSheet(name: "cat_idle", frames: [makeIdlePose()], to: dir)
try writeSheet(name: "cat_sit", frames: [makeSitPose()], to: dir)
try writeSheet(name: "cat_sleep", frames: [makeSleepPose()], to: dir)
